Pushing callback dashboard

diff --git a/pipeline/jobs/build.yml b/pipeline/jobs/build.yml
--- a/pipeline/jobs/build.yml
+++ b/pipeline/jobs/build.yml
@@ -121,6 +121,42 @@ jobs:
           echo "****************************************"
           ls -sd --block-size=1 --format=single-column *
           echo "****************************************"
+
+
+
+          ############################################################################################################################
+          ########################################## Start the Export Job for CallBack Dashboard ##########################################
+          ############################################################################################################################
+          
+          aws quicksight start-asset-bundle-export-job --aws-account-id 442426866507 --asset-bundle-export-job-id 'sdge-export-job-CB' --resource-arns "arn:aws:quicksight:us-west-2:442426866507:dashboard/fe3c066d-a7cd-484a-86cd-f14a51b2c11a" --include-all-dependencies --export-format 'QUICKSIGHT_JSON'
+          
+          ###################################
+          ## Extract the dataset json file ##
+          ###################################
+
+          aws quicksight describe-data-set --aws-account-id 442426866507 --data-set-id "481bbd62-7e7e-4062-9240-c8ba256e726f" > current-dataset_cb_data.json
+          
+          echo "Present Working directory :  $pwd"
+
+          # Code to remove any special chars from the start of json
+          # cat current-dataset_cb_data.json | tr -cd '\11\12\15\40-\176' > current-dataset_cb_data.json
+          
+          ############################################################################
+          ###             Extract the dataset part from the entire json          #####
+          ############################################################################
+
+          jq '.DataSet' current-dataset_cb_data.json > dataset_cb_data.json
+
+          ############################################################################
+          ###        Delete the unnecessary parts from the entire json           #####
+          ############################################################################
+
+          jq 'del(.Arn, .CreatedTime, .LastUpdatedTime, .OutputColumns, .ConsumedSpiceCapacityInBytes)' dataset_cb_data.json > updated-dataset_cb_data.json
+          
+          echo "After formatting the dataset CB, the contents of dir are :"
+          echo "****************************************"
+          ls -sd --block-size=1 --format=single-column *
+          echo "****************************************"
           
           awsAccountId="442426866507"
           jobId="sdge-export-job-IVR"
@@ -210,6 +246,50 @@ jobs:
                 exit 1
             fi
           done
+
+          awsAccountId="442426866507"
+          jobId="sdge-export-job-CB"
+          
+          ############################################################################################################################
+          ########################################## Download the bundle for CB Dashboard  ##########################################
+          ############################################################################################################################
+
+          while true; do
+
+            #########################
+            ## Get the job details ##
+            #########################
+
+            response=$(aws quicksight describe-asset-bundle-export-job --aws-account-id $awsAccountId --asset-bundle-export-job-id $jobId)
+            
+            ##################################################
+            ##     Check if the command was successful      ##
+            ##################################################
+
+            if [ $? -eq 0 ]; then
+                jobStatus=$(echo $response | grep -o '"JobStatus": "[^"]*' | grep -o '[^"]*$')
+                if [ "$jobStatus" == "SUCCESSFUL" ]; then
+                    downloadUrl=$(echo $response | grep -o '"DownloadUrl": "[^"]*' | grep -o '[^"]*$')
+
+                    ##################################################
+                    ###         Download the qs json file          ###
+                    ##################################################
+
+                    curl -o "./assetbundle-sdge-export-job-CB.qs" $downloadUrl
+                    
+                    echo "File downloaded successfully for CB"
+                    break
+                else
+                    echo "Job status is not successful: $jobStatus"
+                    sleep 10
+                fi
+            else
+                echo "Failed to get the job details"
+                exit 1
+            fi
+          done
+
+
         else
             echo "Failed to assume role."
             exit 1
@@ -235,6 +315,10 @@ jobs:
     - publish: assetbundle-sdge-export-job-FCR.qs
       artifact: QS_Bundle_FCR
       displayName: 'Publish the FCR Quicksight artifact to the pipeline'
+
+    - publish: assetbundle-sdge-export-job-CB.qs
+      artifact: QS_Bundle_CB
+      displayName: 'Publish the CB Quicksight artifact to the pipeline'
 
     - publish: updated-dataset_fcr_data.json
       artifact: QS_Bundle_FCR_Dataset
diff --git a/pipeline/steps/pre-tf-steps.yml b/pipeline/steps/pre-tf-steps.yml
--- a/pipeline/steps/pre-tf-steps.yml
+++ b/pipeline/steps/pre-tf-steps.yml
@@ -163,6 +163,65 @@ steps:
             exit 1
         fi
       done
+
+      jobId="sdge-export-job-CB"
+        
+        #####################################
+        ## Asset bundle import job for CB ##
+        #####################################
+        
+        echo "Started the asset bundle import job for CB"
+        echo "The response of import job is :"
+        aws quicksight start-asset-bundle-import-job --aws-account-id "$(awsAccount)" --asset-bundle-import-job-id 'sdge-export-job-CB' --asset-bundle-import-source-bytes fileb://$(Pipeline.Workspace)/QS_Bundle_CB/assetbundle-sdge-export-job-CB.qs --failure-action ROLLBACK
+
+
+        while true; do
+
+            #########################
+            ## Get the job details ##
+            #########################
+
+            response=$(aws quicksight describe-asset-bundle-import-job --aws-account-id "$(awsAccount)" --asset-bundle-import-job-id $jobId)
+            
+            #########################################
+            ## Check if the command was successful ##
+            #########################################
+
+            if [ $? -eq 0 ]; then
+
+                jobStatus=$(echo $response | grep -o '"JobStatus": "[^"]*' | grep -o '[^"]*$')
+
+                if [ "$jobStatus" == "SUCCESSFUL" ]; then
+
+                    echo "CB Quicksight Package deployed"
+                    echo "Updating the CB Dataset!"
+
+                    ######################################################
+                    ## Updating the dataset after dashboard is deployed ##
+                    ######################################################
+
+                    ##############################################################################
+                    ## Updating the physical dataset map in dataset after dashboard is deployed ##
+                    ##############################################################################
+
+                    jq '.PhysicalTableMap."1ca2f1a3-c103-4722-865b-90a8296dc84e".RelationalTable.DataSourceArn = "arn:aws:quicksight:us-west-2:$(awsAccount):datasource/1426d8fa-5420-4b29-88b3-6ca15dbf6472" | .PhysicalTableMap."1ca2f1a3-c103-4722-865b-90a8296dc84e".RelationalTable.Schema = "sdge-dcctr-$(qstargetenv)-wus2-ccc-analytics-connect-datalake-views"' $(Pipeline.Workspace)/QS_Bundle_CB_Dataset/updated-dataset_cb_data.json > current-dataset_cb_data.json
+                    aws quicksight update-data-set --aws-account-id "$(awsAccount)" --data-set-id "ce88acbd-2b70-42a4-af08-4d5ebd0b6181" --cli-input-json fileb://current-dataset_cb_data.json
+                    
+                    break
+                else
+                    echo "Job status is not successful: $jobStatus"
+                    sleep 10
+                fi
+            else
+                echo "Failed to get the job details"
+                exit 1
+            fi
+        done
+
+
+
+
+
     else
         echo "Failed to assume role"
         exit 1
