pushing FCR Dashboard

diff --git a/pipeline/jobs/build.yml b/pipeline/jobs/build.yml
--- a/pipeline/jobs/build.yml
+++ b/pipeline/jobs/build.yml
@@ -62,32 +62,33 @@ jobs:
             fi
           done
 
-          # awsAccountId="442426866507"
-          # jobId="sdge-export-job-WBDB"
           
-          # while true; do
-          #   # Get the job details
-          #   response=$(aws quicksight describe-asset-bundle-export-job --aws-account-id $awsAccountId --asset-bundle-export-job-id $jobId)
+          awsAccountId="442426866507"
+          jobId="sdge-export-job-FCR"
+          
+          while true; do
+            # Get the job details
+            response=$(aws quicksight describe-asset-bundle-export-job --aws-account-id $awsAccountId --asset-bundle-export-job-id $jobId)
 
-          #   # Check if the command was successful
-          #   if [ $? -eq 0 ]; then
-          #       jobStatus=$(echo $response | grep -o '"JobStatus": "[^"]*' | grep -o '[^"]*$')
-          #       if [ "$jobStatus" == "SUCCESSFUL" ]; then
-          #           downloadUrl=$(echo $response | grep -o '"DownloadUrl": "[^"]*' | grep -o '[^"]*$')
-          #           # Download the file
-          #           curl -o "./assetbundle-sdge-export-job-WBDB.qs" $downloadUrl
-          #           ls
-          #           echo "File downloaded successfully WBDB"
-          #           break
-          #       else
-          #           echo "Job status is not successful: $jobStatus"
-          #           sleep 10
-          #       fi
-          #   else
-          #       echo "Failed to get the job details"
-          #       exit 1
-          #   fi
-          # done
+            # Check if the command was successful
+            if [ $? -eq 0 ]; then
+                jobStatus=$(echo $response | grep -o '"JobStatus": "[^"]*' | grep -o '[^"]*$')
+                if [ "$jobStatus" == "SUCCESSFUL" ]; then
+                    downloadUrl=$(echo $response | grep -o '"DownloadUrl": "[^"]*' | grep -o '[^"]*$')
+                    # Download the file
+                    curl -o "./assetbundle-sdge-export-job-FCR.qs" $downloadUrl
+                    ls
+                    echo "File downloaded successfully FCR"
+                    break
+                else
+                    echo "Job status is not successful: $jobStatus"
+                    sleep 10
+                fi
+            else
+                echo "Failed to get the job details"
+                exit 1
+            fi
+          done
         else
             echo "Failed to assume role."
             exit 1
@@ -110,6 +111,6 @@ jobs:
       artifact: QS_Bundle_IVR
       displayName: 'Publish the IVR Quicksight artifact to the pipeline'
 
-    # - publish: assetbundle-sdge-export-job-WBDB.qs
-    #   artifact: QS_Bundle_WBDB
-    #   displayName: 'Publish the WBDB Quicksight artifact to the pipeline'
+    - publish: assetbundle-sdge-export-job-FCR.qs
+      artifact: QS_Bundle_FCR
+      displayName: 'Publish the FCR Quicksight artifact to the pipeline'
diff --git a/pipeline/steps/pre-tf-steps.yml b/pipeline/steps/pre-tf-steps.yml
--- a/pipeline/steps/pre-tf-steps.yml
+++ b/pipeline/steps/pre-tf-steps.yml
@@ -71,30 +71,30 @@ steps:
             fi
         done
 
-    #   aws quicksight start-asset-bundle-import-job --aws-account-id "$(awsAccount)" --asset-bundle-import-job-id 'sdge-export-job-WBDB' --asset-bundle-import-source-bytes fileb://$(Pipeline.Workspace)/QS_Bundle_WBDB/assetbundle-sdge-export-job-WBDB.qs  --failure-action ROLLBACK
+      aws quicksight start-asset-bundle-import-job --aws-account-id "$(awsAccount)" --asset-bundle-import-job-id 'sdge-export-job-FCR' --asset-bundle-import-source-bytes fileb://$(Pipeline.Workspace)/QS_Bundle_FCR/assetbundle-sdge-export-job-FCR.qs  --failure-action ROLLBACK
 
-    #   jobId="sdge-export-job-WBDB"
+      jobId="sdge-export-job-FCR"
       
-    #   while true; do
-    #     # Get the job details
-    #     response=$(aws quicksight describe-asset-bundle-import-job --aws-account-id "$(awsAccount)" --asset-bundle-import-job-id $jobId)
+      while true; do
+        # Get the job details
+        response=$(aws quicksight describe-asset-bundle-import-job --aws-account-id "$(awsAccount)" --asset-bundle-import-job-id $jobId)
 
-    #     # Check if the command was successful
-    #     if [ $? -eq 0 ]; then
-    #         jobStatus=$(echo $response | grep -o '"JobStatus": "[^"]*' | grep -o '[^"]*$')
-    #         if [ "$jobStatus" == "SUCCESSFUL" ]; then
-    #             echo "Quicksight Package deployed"
-    #             aws quicksight update-data-set --aws-account-id "$(awsAccount)" --data-set-id "168c6220-5dbd-4a73-a6fb-caa0553084f0" --name "connectapi" --physical-table-map "{\"38939462-7280-4626-8dc7-c1bbe70d09cd\":{\"RelationalTable\":{\"DataSourceArn\":\"arn:aws:quicksight:us-west-2:"$(awsAccount)":datasource/d6d5c21d-d1be-4895-9256-3fbf8222a4c7\",\"Catalog\":\"AwsDataCatalog\",\"Schema\":\"$(qstargetenv)_connectdatalake\",\"Name\":\"connectapi\",\"InputColumns\":[{\"Name\":\"queue_id\",\"Type\":\"STRING\"},{\"Name\":\"metrics\",\"Type\":\"STRING\"},{\"Name\":\"metric_value\",\"Type\":\"DECIMAL\"},{\"Name\":\"language\",\"Type\":\"STRING\"},{\"Name\":\"type\",\"Type\":\"STRING\"},{\"Name\":\"ess2\",\"Type\":\"STRING\"}]}}}" --import-mode DIRECT_QUERY --logical-table-map "{\"25b1f640-9223-4d94-9927-fd52122f730c\":{\"Alias\":\"connectapi\",\"DataTransforms\":[{\"ProjectOperation\":{\"ProjectedColumns\":[\"queue_id\",\"metrics\",\"metric_value\",\"language\",\"type\",\"ess2\"]}}],\"Source\":{\"PhysicalTableId\":\"38939462-7280-4626-8dc7-c1bbe70d09cd\"}}}"
-    #             break
-    #         else
-    #             echo "Job status is not successful: $jobStatus"
-    #             sleep 10
-    #         fi
-    #     else
-    #         echo "Failed to get the job details"
-    #         exit 1
-    #     fi
-    #   done
+        # Check if the command was successful
+        if [ $? -eq 0 ]; then
+            jobStatus=$(echo $response | grep -o '"JobStatus": "[^"]*' | grep -o '[^"]*$')
+            if [ "$jobStatus" == "SUCCESSFUL" ]; then
+                echo "Quicksight Package deployed"
+                aws quicksight update-data-set --aws-account-id "$(awsAccount)" --data-set-id "5415cb9d-8804-40a3-be67-fced1f075a57" --name "fcr_data_view" --import-mode SPICE --physical-table-map "{\"6ed40859-623a-4e99-95cd-598e66904f1d\":{\"RelationalTable\":{\"DataSourceArn\":\"arn:aws:quicksight:us-west-2:"$(awsAccount)":datasource/37ac4bb8-2adc-4dbb-8b65-280e20c0dccd\",\"Catalog\":\"AwsDataCatalog\",\"Schema\":\"sdge-dcctr-$(qstargetenv)-wus2-ccc-analytics-connect-datalake-views\",\"Name\":\"fcr_data_view\",\"InputColumns\":[{\"Name\":\"customer_endpoint_address\",\"Type\":\"STRING\"},{\"Name\":\"contact_id\",\"Type\":\"STRING\"},{\"Name\":\"queue_enqueue_timestamp\",\"Type\":\"DATETIME\"},{\"Name\":\"agent_username\",\"Type\":\"STRING\"},{\"Name\":\"requested_call_type\",\"Type\":\"STRING\"},{\"Name\":\"actual_call_type\",\"Type\":\"STRING\"},{\"Name\":\"initiation_timestamp_original\",\"Type\":\"DATETIME\"},{\"Name\":\"initiation_timestamp\",\"Type\":\"DATETIME\"},{\"Name\":\"disconnect_timestamp\",\"Type\":\"DATETIME\"},{\"Name\":\"time_difference_seconds\",\"Type\":\"INTEGER\"},{\"Name\":\"year\",\"Type\":\"STRING\"}]}}}" --logical-table-map "{\"dd762542-723e-4a3e-b566-ff58af91f4a0\":{\"Alias\":\"fcr_data_view\",\"DataTransforms\":[{\"ProjectOperation\":{\"ProjectedColumns\":[\"customer_endpoint_address\",\"contact_id\",\"queue_enqueue_timestamp\",\"agent_username\",\"requested_call_type\",\"actual_call_type\",\"initiation_timestamp_original\",\"initiation_timestamp\",\"disconnect_timestamp\",\"time_difference_seconds\",\"year\"]}}],\"Source\":{\"PhysicalTableId\":\"6ed40859-623a-4e99-95cd-598e66904f1d\"}}}"
+                break
+            else
+                echo "Job status is not successful: $jobStatus"
+                sleep 10
+            fi
+        else
+            echo "Failed to get the job details"
+            exit 1
+        fi
+      done
     else
         echo "Failed to assume role."
         exit 1
