uncommented the changes

diff --git a/pipeline/steps/deploy-to-env.yml b/pipeline/steps/deploy-to-env.yml
--- a/pipeline/steps/deploy-to-env.yml
+++ b/pipeline/steps/deploy-to-env.yml
@@ -20,68 +20,68 @@ steps:
     displayName: 'Create VENV'
 
   - script: |
-      # #########################################################
-      # ###  Export AWS credentials from pipeline variables   ###
-      # #########################################################
+      #########################################################
+      ###  Export AWS credentials from pipeline variables   ###
+      #########################################################
 
-      # export AWS_ACCESS_KEY_ID=$(aws-access-key-id)
-      # export AWS_SECRET_ACCESS_KEY=$(aws-secret-access-key-id)
+      export AWS_ACCESS_KEY_ID=$(aws-access-key-id)
+      export AWS_SECRET_ACCESS_KEY=$(aws-secret-access-key-id)
 
-      # #########################################################
-      # #####               Set the AWS region              #####
-      # #########################################################
-      # export AWS_DEFAULT_REGION="us-west-2"
-      # OUTPUT_PROFILE="AWSCLI-AssumeRole" 
+      #########################################################
+      #####               Set the AWS region              #####
+      #########################################################
+      export AWS_DEFAULT_REGION="us-west-2"
+      OUTPUT_PROFILE="AWSCLI-AssumeRole" 
 
-      # #########################################################
-      # ###### Assume the role and capture the credentials ######
-      # #########################################################
+      #########################################################
+      ###### Assume the role and capture the credentials ######
+      #########################################################
 
-      # echo "Assuming role..."
-      # # echo "arn:aws:iam::$(awsAccount):role/fondo/sdge-dcctr-$(Environment)-terraform-oidc-role"
+      echo "Assuming role..."
+      # echo "arn:aws:iam::$(awsAccount):role/fondo/sdge-dcctr-$(Environment)-terraform-oidc-role"
       
-      # ASSUME_ROLE_OUTPUT=$(aws sts assume-role --role-arn "arn:aws:iam::$(awsAccount):role/fondo/sdge-dcctr-$(Environment)-iam-role-ado" --role-session-name "$OUTPUT_PROFILE" --output json)
+      ASSUME_ROLE_OUTPUT=$(aws sts assume-role --role-arn "arn:aws:iam::$(awsAccount):role/fondo/sdge-dcctr-$(Environment)-iam-role-ado" --role-session-name "$OUTPUT_PROFILE" --output json)
       
-      # #########################################################
-      # #### Check if the assume-role command was successful ####
-      # #########################################################
+      #########################################################
+      #### Check if the assume-role command was successful ####
+      #########################################################
 
-      # if [ $? -eq 0 ]; then
-      #   ############################################
-      #   #   Extract credentials from assumed role  #
-      #   ############################################
+      if [ $? -eq 0 ]; then
+        ############################################
+        #   Extract credentials from assumed role  #
+        ############################################
 
-      #   ACCESS_KEY=$(echo $ASSUME_ROLE_OUTPUT | jq -r '.Credentials.AccessKeyId')
-      #   SECRET_KEY=$(echo $ASSUME_ROLE_OUTPUT | jq -r '.Credentials.SecretAccessKey')
-      #   SESSION_TOKEN=$(echo $ASSUME_ROLE_OUTPUT | jq -r '.Credentials.SessionToken')
+        ACCESS_KEY=$(echo $ASSUME_ROLE_OUTPUT | jq -r '.Credentials.AccessKeyId')
+        SECRET_KEY=$(echo $ASSUME_ROLE_OUTPUT | jq -r '.Credentials.SecretAccessKey')
+        SESSION_TOKEN=$(echo $ASSUME_ROLE_OUTPUT | jq -r '.Credentials.SessionToken')
 
-      #   ######################################################################
-      #   # Export the new session credentials for subsequent AWS CLI commands #
-      #   ######################################################################
+        ######################################################################
+        # Export the new session credentials for subsequent AWS CLI commands #
+        ######################################################################
 
-      #   export AWS_ACCESS_KEY_ID=$ACCESS_KEY
-      #   export AWS_SECRET_ACCESS_KEY=$SECRET_KEY
-      #   export AWS_SESSION_TOKEN=$SESSION_TOKEN
+        export AWS_ACCESS_KEY_ID=$ACCESS_KEY
+        export AWS_SECRET_ACCESS_KEY=$SECRET_KEY
+        export AWS_SESSION_TOKEN=$SESSION_TOKEN
 
-      #   ######################################################################
-      #   #### Optionally, print the assumed role ARN for confirmation     #####
-      #   ######################################################################
+        ######################################################################
+        #### Optionally, print the assumed role ARN for confirmation     #####
+        ######################################################################
         
-      #   ASSUMED_ROLE_ARN=$(echo $ASSUME_ROLE_OUTPUT | jq -r '.AssumedRoleUser.Arn')
-      #   echo "Assumed role ARN: $ASSUMED_ROLE_ARN"
-      #   echo "Running Python file from artifacts!"
-      #   python $(Pipeline.Workspace)/ivr_call_transactions/ivr_call_transactions.py "$(Environment)"
-      #   echo "ivr_call_transactions view script run complete!"
-      #   python $(Pipeline.Workspace)/ivr_call_events/ivr_call_events.py "$(Environment)"
-      #   echo "ivr_call_events view script run complete!"
-      #   python $(Pipeline.Workspace)/fcr_data_view/fcr_data_view.py "$(Environment)"
-      #   echo "fcr_data_view script run complete!"
-      #   python $(Pipeline.Workspace)/fcr_boxplot_view/fcr_boxplot_view.py "$(Environment)"
-      #   echo "fcr_data_view script run complete!"
-      # else
-      #   echo "Failed to assume role."
-      #   exit 1
-      # fi
+        ASSUMED_ROLE_ARN=$(echo $ASSUME_ROLE_OUTPUT | jq -r '.AssumedRoleUser.Arn')
+        echo "Assumed role ARN: $ASSUMED_ROLE_ARN"
+        echo "Running Python file from artifacts!"
+        python $(Pipeline.Workspace)/ivr_call_transactions/ivr_call_transactions.py "$(Environment)"
+        echo "ivr_call_transactions view script run complete!"
+        python $(Pipeline.Workspace)/ivr_call_events/ivr_call_events.py "$(Environment)"
+        echo "ivr_call_events view script run complete!"
+        python $(Pipeline.Workspace)/fcr_data_view/fcr_data_view.py "$(Environment)"
+        echo "fcr_data_view script run complete!"
+        python $(Pipeline.Workspace)/fcr_boxplot_view/fcr_boxplot_view.py "$(Environment)"
+        echo "fcr_data_view script run complete!"
+      else
+        echo "Failed to assume role."
+        exit 1
+      fi
       
     displayName: 'Assume ADO Role to run PY Scripts'
 
