added QS code

diff --git a/pipeline/steps/pre-tf-steps.yml b/pipeline/steps/pre-tf-steps.yml
--- a/pipeline/steps/pre-tf-steps.yml
+++ b/pipeline/steps/pre-tf-steps.yml
@@ -1,3 +1,92 @@
 steps:
-  - script: |
-      echo "Hello World"
+- script: |
+    echo "Use Pipeline Artifact and deploy to env"
+    # Export AWS credentials from pipeline variables
+    export AWS_ACCESS_KEY_ID=$(aws-access-key-id)
+    export AWS_SECRET_ACCESS_KEY=$(aws-secret-access-key-id)
+    # Set the AWS region
+    export AWS_DEFAULT_REGION="us-west-2"
+    OUTPUT_PROFILE="AWSCLI-AssumeRole" 
+
+    # Assume the role and capture the credentials
+    echo "Assuming role..."
+    echo "$(awsAssumeRole)"
+    # ASSUME_ROLE_OUTPUT=$(aws sts assume-role --role-arn "$(awsAssumeRole)" --role-session-name "$OUTPUT_PROFILE" --output json)
+
+    ASSUME_ROLE_OUTPUT=$(aws sts assume-role --role-arn "arn:aws:iam::$(awsAccount):role/fondo/sdge-dcctr-$(Environment)-terraform-oidc-role" --role-session-name "$OUTPUT_PROFILE" --output json)
+    # Check if the assume-role command was successful
+
+    if [ $? -eq 0 ]; then
+      # Extract credentials
+      ACCESS_KEY=$(echo $ASSUME_ROLE_OUTPUT | jq -r '.Credentials.AccessKeyId')
+      SECRET_KEY=$(echo $ASSUME_ROLE_OUTPUT | jq -r '.Credentials.SecretAccessKey')
+      SESSION_TOKEN=$(echo $ASSUME_ROLE_OUTPUT | jq -r '.Credentials.SessionToken')
+      # Export the new session credentials for subsequent AWS CLI commands
+      export AWS_ACCESS_KEY_ID=$ACCESS_KEY
+      export AWS_SECRET_ACCESS_KEY=$SECRET_KEY
+      export AWS_SESSION_TOKEN=$SESSION_TOKEN
+      ASSUMED_ROLE_ARN=$(echo $ASSUME_ROLE_OUTPUT | jq -r '.AssumedRoleUser.Arn')
+      echo "Assumed role ARN: $ASSUMED_ROLE_ARN"
+      echo "Creating the quicksight file!"
+      ls
+      echo $(Pipeline.Workspace) 
+  
+      aws quicksight start-asset-bundle-import-job --aws-account-id "$(awsAccount)" --asset-bundle-import-job-id 'sdge-export-job-IVR' --asset-bundle-import-source-bytes fileb://$(Pipeline.Workspace)/QS_Bundle_IVR/assetbundle-sdge-export-job-IVR.qs --override-parameters "{\"DataSources\":[{\"DataSourceId\":\"867d6f11-6f0a-4f40-b865-6a0cc5baf78f\",\"Name\":\"$(qstargetenv)_connectdatalake\",\"DataSourceParameters\":{\"AthenaParameters\":{\"WorkGroup\":\"primary\"}},\"SslProperties\":{\"DisableSsl\":false}}],\"DataSets\":[{\"DataSetId\":\"2637d8cd-26a2-4075-943d-9ed0a7e94946\",\"Name\":\"ivr_combined_2509data_ext_table\"}]}" --failure-action ROLLBACK
+
+
+      
+      jobId="sdge-export-job-IVR"
+      
+      while true; do
+        # Get the job details
+        response=$(aws quicksight describe-asset-bundle-import-job --aws-account-id "$(awsAccount)" --asset-bundle-import-job-id $jobId)
+
+        # Check if the command was successful
+        if [ $? -eq 0 ]; then
+            jobStatus=$(echo $response | grep -o '"JobStatus": "[^"]*' | grep -o '[^"]*$')
+            if [ "$jobStatus" == "SUCCESSFUL" ]; then
+                echo "Quicksight Package deployed"
+                aws quicksight update-data-set --aws-account-id "$(awsAccount)" --data-set-id "2637d8cd-26a2-4075-943d-9ed0a7e94946" --name "ivr_combined_2509data_ext_table" --physical-table-map "{\"c2576ff2-6a9a-4315-832b-4038396a5248\":{\"RelationalTable\":{\"DataSourceArn\":\"arn:aws:quicksight:us-west-2:"$(awsAccount)":datasource/867d6f11-6f0a-4f40-b865-6a0cc5baf78f\",\"Catalog\":\"AwsDataCatalog\",\"Schema\":\"$(qstargetenv)_connectdatalake\",\"Name\":\"ivr_combined_2509data_ext_table\",\"InputColumns\":[{\"Name\":\"contact_id\",\"Type\":\"STRING\"},{\"Name\":\"channel\",\"Type\":\"STRING\"},{\"Name\":\"initiation_method\",\"Type\":\"STRING\"},{\"Name\":\"is_queued\",\"Type\":\"INTEGER\"},{\"Name\":\"attributes\",\"Type\":\"STRING\"},{\"Name\":\"call_start_date_time\",\"Type\":\"STRING\"},{\"Name\":\"call_end_reason\",\"Type\":\"STRING\"},{\"Name\":\"caller_phone_number\",\"Type\":\"STRING\"},{\"Name\":\"day_of_week\",\"Type\":\"STRING\"},{\"Name\":\"weekday_check\",\"Type\":\"STRING\"},{\"Name\":\"date\",\"Type\":\"DATETIME\"},{\"Name\":\"curtailmentflag\",\"Type\":\"STRING\"},{\"Name\":\"l3_tag\",\"Type\":\"STRING\"},{\"Name\":\"l1_tag\",\"Type\":\"STRING\"},{\"Name\":\"l2_tag\",\"Type\":\"STRING\"}]}}}" --import-mode SPICE --logical-table-map "{\"5cb33d9a-78b1-4cc3-91e2-e40ee2fa12a7\":{\"Alias\":\"ivr_combined_2509data_ext_table\",\"DataTransforms\":[{\"ProjectOperation\":{\"ProjectedColumns\":[\"contact_id\",\"channel\",\"initiation_method\",\"is_queued\",\"attributes\",\"call_start_date_time\",\"call_end_reason\",\"caller_phone_number\",\"day_of_week\",\"weekday_check\",\"date\",\"curtailmentflag\",\"l3_tag\",\"l1_tag\",\"l2_tag\"]}}],\"Source\":{\"PhysicalTableId\":\"c2576ff2-6a9a-4315-832b-4038396a5248\"}}}" --field-folders '{}'
+                
+
+                break
+            else
+                echo "Job status is not successful: $jobStatus"
+                sleep 10
+            fi
+        else
+            echo "Failed to get the job details"
+            exit 1
+        fi
+      done
+      aws quicksight start-asset-bundle-import-job --aws-account-id "$(awsAccount)" --asset-bundle-import-job-id 'sdge-export-job-WBDB' --asset-bundle-import-source-bytes fileb://$(Pipeline.Workspace)/QS_Bundle_WBDB/assetbundle-sdge-export-job-WBDB.qs  --failure-action ROLLBACK
+
+      jobId="sdge-export-job-WBDB"
+      
+      while true; do
+        # Get the job details
+        response=$(aws quicksight describe-asset-bundle-import-job --aws-account-id "$(awsAccount)" --asset-bundle-import-job-id $jobId)
+
+        # Check if the command was successful
+        if [ $? -eq 0 ]; then
+            jobStatus=$(echo $response | grep -o '"JobStatus": "[^"]*' | grep -o '[^"]*$')
+            if [ "$jobStatus" == "SUCCESSFUL" ]; then
+                echo "Quicksight Package deployed"
+                aws quicksight update-data-set --aws-account-id "$(awsAccount)" --data-set-id "79aa2ef2-26e0-498f-a4f3-81864c4976cd" --name "test_dg_new" --physical-table-map "{\"aede2570-91ef-47f0-a921-af6db1977b43\":{\"RelationalTable\":{\"DataSourceArn\":\"arn:aws:quicksight:us-west-2:442426866507:datasource/570ee17d-5c34-4add-93c0-d8f2141d3a77\",\"Catalog\":\"AwsDataCatalog\",\"Schema\":\"connect_sampledata_api\",\"Name\":\"test_dg_new\",\"InputColumns\":[{\"Name\":\"queue_id\",\"Type\":\"STRING\"},{\"Name\":\"metrics\",\"Type\":\"STRING\"},{\"Name\":\"metric_value\",\"Type\":\"INTEGER\"},{\"Name\":\"language\",\"Type\":\"STRING\"},{\"Name\":\"type\",\"Type\":\"STRING\"},{\"Name\":\"ess2\",\"Type\":\"STRING\"}]}}}" --import-mode DIRECT_QUERY --logical-table-map "{\"180d96d4-a8d1-4306-be4e-273a558366ee\":{\"Alias\":\"test_dg_new\",\"Source\":{\"PhysicalTableId\":\"aede2570-91ef-47f0-a921-af6db1977b43\"}}}"
+                break
+            else
+                echo "Job status is not successful: $jobStatus"
+                sleep 10
+            fi
+        else
+            echo "Failed to get the job details"
+            exit 1
+        fi
+      done
+    else
+        echo "Failed to assume role."
+        exit 1
+    fi
+
+  displayName: 'Quicksight Deployment'
+
