commenting the assume ado role to test other resources

diff --git a/pipeline/steps/pre-tf-steps.yml b/pipeline/steps/pre-tf-steps.yml
--- a/pipeline/steps/pre-tf-steps.yml
+++ b/pipeline/steps/pre-tf-steps.yml
@@ -2,174 +2,174 @@ steps:
 - script: |
     echo "Use Pipeline Artifact and deploy to env"
 
-    if [ "$(Environment)" == "dev" ]; then
-      echo "DEV deployment is not required"
-      exit 0
-    fi
+    # if [ "$(Environment)" == "dev" ]; then
+    #   echo "DEV deployment is not required"
+    #   exit 0
+    # fi
 
-    ##################################################
-    # Export AWS credentials from pipeline variables #
-    ##################################################
+    # ##################################################
+    # # Export AWS credentials from pipeline variables #
+    # ##################################################
 
-    export AWS_ACCESS_KEY_ID=$(aws-access-key-id)
-    export AWS_SECRET_ACCESS_KEY=$(aws-secret-access-key-id)
+    # export AWS_ACCESS_KEY_ID=$(aws-access-key-id)
+    # export AWS_SECRET_ACCESS_KEY=$(aws-secret-access-key-id)
 
-    ##################################################
-    ############## Set the AWS region ################
-    ##################################################
+    # ##################################################
+    # ############## Set the AWS region ################
+    # ##################################################
 
-    export AWS_DEFAULT_REGION="us-west-2"
-    OUTPUT_PROFILE="AWSCLI-AssumeRole"
+    # export AWS_DEFAULT_REGION="us-west-2"
+    # OUTPUT_PROFILE="AWSCLI-AssumeRole"
 
-    ###################################################
-    ### Assume the role and capture the credentials ###
-    ###################################################
+    # ###################################################
+    # ### Assume the role and capture the credentials ###
+    # ###################################################
 
-    echo "Assuming the ADO role..."
-    ASSUME_ROLE_OUTPUT=$(aws sts assume-role --role-arn "arn:aws:iam::$(awsAccount):role/fondo/sdge-dcctr-$(Environment)-iam-role-ado" --role-session-name "$OUTPUT_PROFILE" --output json)
+    # echo "Assuming the ADO role..."
+    # ASSUME_ROLE_OUTPUT=$(aws sts assume-role --role-arn "arn:aws:iam::$(awsAccount):role/fondo/sdge-dcctr-$(Environment)-iam-role-ado" --role-session-name "$OUTPUT_PROFILE" --output json)
     
-    #####################################################
-    ## Check if the assume-role command was successful ##
-    #####################################################
+    # #####################################################
+    # ## Check if the assume-role command was successful ##
+    # #####################################################
 
-    if [ $? -eq 0 ]; then
+    # if [ $? -eq 0 ]; then
 
-        #########################
-        ## Extract credentials ##
-        #########################
+    #     #########################
+    #     ## Extract credentials ##
+    #     #########################
 
-        ACCESS_KEY=$(echo $ASSUME_ROLE_OUTPUT | jq -r '.Credentials.AccessKeyId')
-        SECRET_KEY=$(echo $ASSUME_ROLE_OUTPUT | jq -r '.Credentials.SecretAccessKey')
-        SESSION_TOKEN=$(echo $ASSUME_ROLE_OUTPUT | jq -r '.Credentials.SessionToken')
+    #     ACCESS_KEY=$(echo $ASSUME_ROLE_OUTPUT | jq -r '.Credentials.AccessKeyId')
+    #     SECRET_KEY=$(echo $ASSUME_ROLE_OUTPUT | jq -r '.Credentials.SecretAccessKey')
+    #     SESSION_TOKEN=$(echo $ASSUME_ROLE_OUTPUT | jq -r '.Credentials.SessionToken')
 
-        ########################################################################
-        ## Export the new session credentials for subsequent AWS CLI commands ##
-        ########################################################################
+    #     ########################################################################
+    #     ## Export the new session credentials for subsequent AWS CLI commands ##
+    #     ########################################################################
 
-        export AWS_ACCESS_KEY_ID=$ACCESS_KEY
-        export AWS_SECRET_ACCESS_KEY=$SECRET_KEY
-        export AWS_SESSION_TOKEN=$SESSION_TOKEN
-        ASSUMED_ROLE_ARN=$(echo $ASSUME_ROLE_OUTPUT | jq -r '.AssumedRoleUser.Arn')
-        echo "Assumed role ARN: $ASSUMED_ROLE_ARN"
-        echo "Creating the quicksight file!"
+    #     export AWS_ACCESS_KEY_ID=$ACCESS_KEY
+    #     export AWS_SECRET_ACCESS_KEY=$SECRET_KEY
+    #     export AWS_SESSION_TOKEN=$SESSION_TOKEN
+    #     ASSUMED_ROLE_ARN=$(echo $ASSUME_ROLE_OUTPUT | jq -r '.AssumedRoleUser.Arn')
+    #     echo "Assumed role ARN: $ASSUMED_ROLE_ARN"
+    #     echo "Creating the quicksight file!"
         
-        echo "Workspace details: "
-        echo $(Pipeline.Workspace)
-        echo "========================="
+    #     echo "Workspace details: "
+    #     echo $(Pipeline.Workspace)
+    #     echo "========================="
 
-        jobId="sdge-export-job-IVR"
+    #     jobId="sdge-export-job-IVR"
         
-        #####################################
-        ## Asset bundle import job for IVR ##
-        #####################################
+    #     #####################################
+    #     ## Asset bundle import job for IVR ##
+    #     #####################################
         
-        echo "Started the asset bundle import job for IVR"
-        echo "The response of import job is :"
-        aws quicksight start-asset-bundle-import-job --aws-account-id "$(awsAccount)" --asset-bundle-import-job-id 'sdge-export-job-IVR' --asset-bundle-import-source-bytes fileb://$(Pipeline.Workspace)/QS_Bundle_IVR/assetbundle-sdge-export-job-IVR.qs --override-parameters "{\"DataSources\":[{\"DataSourceId\":\"867d6f11-6f0a-4f40-b865-6a0cc5baf78f\",\"Name\":\"$(qstargetenv)_connectdatalake\",\"DataSourceParameters\":{\"AthenaParameters\":{\"WorkGroup\":\"primary\"}},\"SslProperties\":{\"DisableSsl\":false}}],\"DataSets\":[{\"DataSetId\":\"2637d8cd-26a2-4075-943d-9ed0a7e94946\",\"Name\":\"ivr_combined_2509data_ext_table\"}]}" --failure-action ROLLBACK
+    #     echo "Started the asset bundle import job for IVR"
+    #     echo "The response of import job is :"
+    #     aws quicksight start-asset-bundle-import-job --aws-account-id "$(awsAccount)" --asset-bundle-import-job-id 'sdge-export-job-IVR' --asset-bundle-import-source-bytes fileb://$(Pipeline.Workspace)/QS_Bundle_IVR/assetbundle-sdge-export-job-IVR.qs --override-parameters "{\"DataSources\":[{\"DataSourceId\":\"867d6f11-6f0a-4f40-b865-6a0cc5baf78f\",\"Name\":\"$(qstargetenv)_connectdatalake\",\"DataSourceParameters\":{\"AthenaParameters\":{\"WorkGroup\":\"primary\"}},\"SslProperties\":{\"DisableSsl\":false}}],\"DataSets\":[{\"DataSetId\":\"2637d8cd-26a2-4075-943d-9ed0a7e94946\",\"Name\":\"ivr_combined_2509data_ext_table\"}]}" --failure-action ROLLBACK
 
 
-        while true; do
+    #     while true; do
 
-            #########################
-            ## Get the job details ##
-            #########################
+    #         #########################
+    #         ## Get the job details ##
+    #         #########################
 
-            response=$(aws quicksight describe-asset-bundle-import-job --aws-account-id "$(awsAccount)" --asset-bundle-import-job-id $jobId)
+    #         response=$(aws quicksight describe-asset-bundle-import-job --aws-account-id "$(awsAccount)" --asset-bundle-import-job-id $jobId)
             
-            #########################################
-            ## Check if the command was successful ##
-            #########################################
+    #         #########################################
+    #         ## Check if the command was successful ##
+    #         #########################################
 
-            if [ $? -eq 0 ]; then
+    #         if [ $? -eq 0 ]; then
 
-                jobStatus=$(echo $response | grep -o '"JobStatus": "[^"]*' | grep -o '[^"]*$')
+    #             jobStatus=$(echo $response | grep -o '"JobStatus": "[^"]*' | grep -o '[^"]*$')
 
-                if [ "$jobStatus" == "SUCCESSFUL" ]; then
+    #             if [ "$jobStatus" == "SUCCESSFUL" ]; then
 
-                    echo "IVR Quicksight Package deployed"
-                    echo "Updating the IVR Dataset!"
+    #                 echo "IVR Quicksight Package deployed"
+    #                 echo "Updating the IVR Dataset!"
 
-                    ######################################################
-                    ## Updating the dataset after dashboard is deployed ##
-                    ######################################################
+    #                 ######################################################
+    #                 ## Updating the dataset after dashboard is deployed ##
+    #                 ######################################################
 
-                    ##############################################################################
-                    ## Updating the physical dataset map in dataset after dashboard is deployed ##
-                    ##############################################################################
+    #                 ##############################################################################
+    #                 ## Updating the physical dataset map in dataset after dashboard is deployed ##
+    #                 ##############################################################################
 
-                    jq '.PhysicalTableMap."3a4e1cf3-3f68-4a46-8c7e-b8d934240134".RelationalTable.DataSourceArn = "arn:aws:quicksight:us-west-2:$(awsAccount):datasource/fd19c252-1725-4e1e-8bff-68a9bbc46cfe" | .PhysicalTableMap."3a4e1cf3-3f68-4a46-8c7e-b8d934240134".RelationalTable.Schema = "sdge-dcctr-$(qstargetenv)-wus2-ccc-analytics-connect-datalake-views" | .PhysicalTableMap."c63258cf-acd2-4d2f-bf5f-8e394b4be2cd".RelationalTable.Schema = "sdge-dcctr-$(qstargetenv)-wus2-ccc-analytics-connect-datalake-views" |  .PhysicalTableMap."c63258cf-acd2-4d2f-bf5f-8e394b4be2cd".RelationalTable.DataSourceArn = "arn:aws:quicksight:us-west-2:$(awsAccount):datasource/3229f118-efa4-4f41-b018-194a244e2c6b"' $(Pipeline.Workspace)/QS_Bundle_IVR_Dataset/updated-dataset_ivr_data.json > current-dataset_ivr_data.json
-                    aws quicksight update-data-set --aws-account-id "$(awsAccount)" --data-set-id "ce88acbd-2b70-42a4-af08-4d5ebd0b6181" --cli-input-json fileb://current-dataset_ivr_data.json
+    #                 jq '.PhysicalTableMap."3a4e1cf3-3f68-4a46-8c7e-b8d934240134".RelationalTable.DataSourceArn = "arn:aws:quicksight:us-west-2:$(awsAccount):datasource/fd19c252-1725-4e1e-8bff-68a9bbc46cfe" | .PhysicalTableMap."3a4e1cf3-3f68-4a46-8c7e-b8d934240134".RelationalTable.Schema = "sdge-dcctr-$(qstargetenv)-wus2-ccc-analytics-connect-datalake-views" | .PhysicalTableMap."c63258cf-acd2-4d2f-bf5f-8e394b4be2cd".RelationalTable.Schema = "sdge-dcctr-$(qstargetenv)-wus2-ccc-analytics-connect-datalake-views" |  .PhysicalTableMap."c63258cf-acd2-4d2f-bf5f-8e394b4be2cd".RelationalTable.DataSourceArn = "arn:aws:quicksight:us-west-2:$(awsAccount):datasource/3229f118-efa4-4f41-b018-194a244e2c6b"' $(Pipeline.Workspace)/QS_Bundle_IVR_Dataset/updated-dataset_ivr_data.json > current-dataset_ivr_data.json
+    #                 aws quicksight update-data-set --aws-account-id "$(awsAccount)" --data-set-id "ce88acbd-2b70-42a4-af08-4d5ebd0b6181" --cli-input-json fileb://current-dataset_ivr_data.json
                     
-                    break
-                else
-                    echo "Job status is not successful: $jobStatus"
-                    sleep 10
-                fi
-            else
-                echo "Failed to get the job details"
-                exit 1
-            fi
-        done
+    #                 break
+    #             else
+    #                 echo "Job status is not successful: $jobStatus"
+    #                 sleep 10
+    #             fi
+    #         else
+    #             echo "Failed to get the job details"
+    #             exit 1
+    #         fi
+    #     done
 
-      #####################################
-      ## Asset bundle import job for FCR ##
-      #####################################
+    #   #####################################
+    #   ## Asset bundle import job for FCR ##
+    #   #####################################
 
-      echo "Started the asset bundle import job for FCR"
-      echo "The response of import job is :"
+    #   echo "Started the asset bundle import job for FCR"
+    #   echo "The response of import job is :"
 
-      aws quicksight start-asset-bundle-import-job --aws-account-id "$(awsAccount)" --asset-bundle-import-job-id 'sdge-export-job-FCR' --asset-bundle-import-source-bytes fileb://$(Pipeline.Workspace)/QS_Bundle_FCR/assetbundle-sdge-export-job-FCR.qs  --failure-action ROLLBACK
+    #   aws quicksight start-asset-bundle-import-job --aws-account-id "$(awsAccount)" --asset-bundle-import-job-id 'sdge-export-job-FCR' --asset-bundle-import-source-bytes fileb://$(Pipeline.Workspace)/QS_Bundle_FCR/assetbundle-sdge-export-job-FCR.qs  --failure-action ROLLBACK
 
-      jobId="sdge-export-job-FCR"
+    #   jobId="sdge-export-job-FCR"
       
 
-      while true; do
+    #   while true; do
 
-        #########################
-        ## Get the job details ##
-        #########################
+    #     #########################
+    #     ## Get the job details ##
+    #     #########################
 
-        response=$(aws quicksight describe-asset-bundle-import-job --aws-account-id "$(awsAccount)" --asset-bundle-import-job-id $jobId)
+    #     response=$(aws quicksight describe-asset-bundle-import-job --aws-account-id "$(awsAccount)" --asset-bundle-import-job-id $jobId)
 
-        #########################################
-        ## Check if the command was successful ##
-        #########################################
+    #     #########################################
+    #     ## Check if the command was successful ##
+    #     #########################################
 
-        if [ $? -eq 0 ]; then
+    #     if [ $? -eq 0 ]; then
 
-            jobStatus=$(echo $response | grep -o '"JobStatus": "[^"]*' | grep -o '[^"]*$')
+    #         jobStatus=$(echo $response | grep -o '"JobStatus": "[^"]*' | grep -o '[^"]*$')
 
-            if [ "$jobStatus" == "SUCCESSFUL" ]; then
-                echo "FCR Quicksight Package deployed"
-                echo "Updating the FCR Dataset"
+    #         if [ "$jobStatus" == "SUCCESSFUL" ]; then
+    #             echo "FCR Quicksight Package deployed"
+    #             echo "Updating the FCR Dataset"
 
-                ######################################################
-                ## Updating the dataset after dashboard is deployed ##
-                ######################################################
+    #             ######################################################
+    #             ## Updating the dataset after dashboard is deployed ##
+    #             ######################################################
 
-                ##############################################################################
-                ## Updating the physical dataset map in dataset after dashboard is deployed ##
-                ##############################################################################
+    #             ##############################################################################
+    #             ## Updating the physical dataset map in dataset after dashboard is deployed ##
+    #             ##############################################################################
                 
-                jq '.PhysicalTableMap."3179445e-3df4-469d-a4be-c78eabe0a896".RelationalTable.DataSourceArn = "arn:aws:quicksight:us-west-2:$(awsAccount):datasource/0bef68f3-8471-49dd-b704-f5904c10f1a9" | .PhysicalTableMap."3179445e-3df4-469d-a4be-c78eabe0a896".RelationalTable.Schema = "sdge-dcctr-$(qstargetenv)-wus2-ccc-analytics-connect-datalake-views"' $(Pipeline.Workspace)/QS_Bundle_FCR_Dataset/updated-dataset_fcr_data.json > current-dataset_fcr_data.json
-                aws quicksight update-data-set --aws-account-id "$(awsAccount)" --data-set-id "3aae9ae4-d55d-4e35-9345-4b657a077079" --cli-input-json fileb://current-dataset_fcr_data.json
+    #             jq '.PhysicalTableMap."3179445e-3df4-469d-a4be-c78eabe0a896".RelationalTable.DataSourceArn = "arn:aws:quicksight:us-west-2:$(awsAccount):datasource/0bef68f3-8471-49dd-b704-f5904c10f1a9" | .PhysicalTableMap."3179445e-3df4-469d-a4be-c78eabe0a896".RelationalTable.Schema = "sdge-dcctr-$(qstargetenv)-wus2-ccc-analytics-connect-datalake-views"' $(Pipeline.Workspace)/QS_Bundle_FCR_Dataset/updated-dataset_fcr_data.json > current-dataset_fcr_data.json
+    #             aws quicksight update-data-set --aws-account-id "$(awsAccount)" --data-set-id "3aae9ae4-d55d-4e35-9345-4b657a077079" --cli-input-json fileb://current-dataset_fcr_data.json
                 
 
-                jq '.PhysicalTableMap."fb9b0834-b17d-43b5-b992-341e00b4e6be".RelationalTable.DataSourceArn = "arn:aws:quicksight:us-west-2:$(awsAccount):datasource/0bef68f3-8471-49dd-b704-f5904c10f1a9" | .PhysicalTableMap."fb9b0834-b17d-43b5-b992-341e00b4e6be".RelationalTable.Schema = "sdge-dcctr-$(qstargetenv)-wus2-ccc-analytics-connect-datalake-views"' $(Pipeline.Workspace)/QS_Bundle_FCR_Dataset_Boxplot/updated-dataset_fcr_boxplot_view.json > current-dataset_fcr_boxplot_view.json
-                aws quicksight update-data-set --aws-account-id "$(awsAccount)" --data-set-id "2a3f7d86-207d-4e64-843c-b212ba5276a5" --cli-input-json fileb://current-dataset_fcr_boxplot_view.json
-                break
-            else
-                echo "Job status is not successful: $jobStatus"
-                sleep 10
-            fi
-        else
-            echo "Failed to get the job details"
-            exit 1
-        fi
-      done
-    else
-        echo "Failed to assume role"
-        exit 1
-    fi
+    #             jq '.PhysicalTableMap."fb9b0834-b17d-43b5-b992-341e00b4e6be".RelationalTable.DataSourceArn = "arn:aws:quicksight:us-west-2:$(awsAccount):datasource/0bef68f3-8471-49dd-b704-f5904c10f1a9" | .PhysicalTableMap."fb9b0834-b17d-43b5-b992-341e00b4e6be".RelationalTable.Schema = "sdge-dcctr-$(qstargetenv)-wus2-ccc-analytics-connect-datalake-views"' $(Pipeline.Workspace)/QS_Bundle_FCR_Dataset_Boxplot/updated-dataset_fcr_boxplot_view.json > current-dataset_fcr_boxplot_view.json
+    #             aws quicksight update-data-set --aws-account-id "$(awsAccount)" --data-set-id "2a3f7d86-207d-4e64-843c-b212ba5276a5" --cli-input-json fileb://current-dataset_fcr_boxplot_view.json
+    #             break
+    #         else
+    #             echo "Job status is not successful: $jobStatus"
+    #             sleep 10
+    #         fi
+    #     else
+    #         echo "Failed to get the job details"
+    #         exit 1
+    #     fi
+    #   done
+    # else
+    #     echo "Failed to assume role"
+    #     exit 1
+    # fi
 
   displayName: 'Quicksight Deployment'
